version: 0.0
os: linux
# files:
#   - source: ./my-app-1.0-SNAPSHOT.jar
#     destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/removePrev.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/runImg.sh
      timeout: 1800
      runas: root