version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t aws-dashboard:latest -t aws-dashboard:1.0 .
#      - docker tag aws-dashboard 042524953207.dkr.ecr.eu-west-1.amazonaws.com/aws-dashboard:1.0
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
#      - docker push 042524953207.dkr.ecr.eu-west-1.amazonaws.com/aws-dashboard:1.0
      - docker push aws-dashboard
